import type {Metadata} from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ToastContainer} from "react-toastify";
import {ChatContext, AuthContextProvider} from "@/context/ChatContext";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
  });


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br" suppressHydrationWarning>
        <body
            className={`${inter.variable} antialiased`}
        >
        <AuthContextProvider>
            <ToastContainer position={"top-right"} autoClose={3000}/>
            {children}
        </AuthContextProvider>
        </body>
        </html>
    );
}
